'use strict';
import galleryItems from '/gallery-items.js';
import { refs } from './refs.js';
import { createGallery } from './createGallery.js';
import { openModal } from './modal.js';
import { closeModal } from './modal.js';
import { onEscPress } from './modal.js';
import { onLightboxClick } from './modal.js';
console.log(galleryItems);
createGallery(galleryItems);
refs.galleryList.addEventListener('click', openModal);
refs.lightboxCloseBtn.addEventListener('click', closeModal);
window.addEventListener('keydown', onEscPress);
refs.lightboxOverlay.addEventListener('click', onLightboxClick);
